#!/bin/sh
mkdir ~/.vim/swap
mkdir ~/.vim/swp
mkdir ~/.vim/backup
mkdir ~/.vim/undo
echo 'Vim directories created!'

ln ~/.config/vim-config/vimrc ~/.vimrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo 'Plug.vim installed!'
echo 'Open vim and execute :PlugInstall'
